spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssgl?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ssgl.entity
server:
  port: 8090
